# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: BANGLAB.
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://midaeng.github.io
baseurl: "/maintest"
# baseurl: ""

# google_analytics: UA-52446115-1
# repo: http://github.com/nandomoreirame/end2end
disqus_shortname: "fernandomoreira"
disqus_site_shortname: "fernandomoreira"

# Author settings
author:
  name      : Mijin Baek
  job       : Agile Coach and Business Analyst
  bio       : "I am an Agile Coach and Business Analyst in Korea."
  thumb     : /images/bio-photo.png
  # github    : http://github.com/nandomoreirame
  # twitter   : http://twitter.com/nandomoreirame
  facebook  : http://facebook.com/dooly.bang
  linkedin  : http://linkedin.com/in/midaeng
  instagram : https://www.instagram.com/bybanglab/
  brunch  : https://brunch.co.kr/@banglab
  youtube : https://www.youtube.com/user/midaeng


# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  - slug: articles
    title: Article
  - slug: soycandle
    title: SoyCandle

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]